import { useMemo, useState } from 'react'
import { specimens, workflow } from './data'
import type { QCStatus, ReportStatus, Slide, Specimen } from './types'
import { Avatar, CaseRow, Icon, KpiCard, Panel, StatusBadge } from './components'

type Page = 'tower' | 'specimens' | 'workflow' | 'slides' | 'quality' | 'reports' | 'analytics' | 'audit'
const nav: { id: Page; label: string; icon: string }[] = [
  { id: 'tower', label: 'Control Tower', icon: 'grid' }, { id: 'specimens', label: 'Specimens', icon: 'flask' }, { id: 'workflow', label: 'Workflow', icon: 'flow' }, { id: 'slides', label: 'Slides', icon: 'slides' }, { id: 'quality', label: 'Quality Control', icon: 'shield' }, { id: 'reports', label: 'Reports', icon: 'file' }, { id: 'analytics', label: 'Analytics', icon: 'chart' }, { id: 'audit', label: 'Audit Trail', icon: 'clock' },
]

export default function App() {
  const [page, setPage] = useState<Page>('tower')
  const [selectedId, setSelectedId] = useState('PATH-004821')
  const [reportStatus, setReportStatus] = useState<ReportStatus>('Under Review')
  const [search, setSearch] = useState('')
  const [toast, setToast] = useState('')
  const selected = specimens.find(s => s.id === selectedId) ?? specimens[0]
  const openSpecimen = (id: string) => { setSelectedId(id); setPage('specimens') }
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2600) }
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><span /></div><div><strong>PATHOFLOW <em>AI</em></strong><small>Laboratory Intelligence</small></div></div>
      <nav>{nav.map(item => <button key={item.id} className={page === item.id ? 'active' : ''} onClick={() => setPage(item.id)}><Icon name={item.icon}/><span>{item.label}</span>{item.id === 'quality' && <b>3</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="lab-status"><i /> Laboratory systems<br/><small>All services operational</small></div><button className="user-switch"><Avatar name="Aria Shah" small/><span>Aria Shah<small>Lab Director</small></span><Icon name="chevron" size={14}/></button></div>
    </aside>
    <main>
      <header className="topbar"><div className="crumb"><span>PathoFlow AI</span><i>/</i><strong>{page === 'tower' ? 'Laboratory Control Tower' : nav.find(x => x.id === page)?.label}</strong></div><div className="top-actions"><label className="global-search"><Icon name="search" size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search specimen, slide, patient..."/></label><button className="icon-button" onClick={() => notify('You have 3 workflow alerts.')}><Icon name="bell"/><b /></button></div></header>
      {page === 'tower' && <Tower onOpen={openSpecimen} onNavigate={setPage} />}
      {page === 'specimens' && <Specimens selected={selected} query={search} onOpen={setSelectedId} onNavigate={setPage} />}
      {page === 'workflow' && <Workflow />}
      {page === 'slides' && <Slides selected={selected} onSelect={setSelectedId} />}
      {page === 'quality' && <Quality selected={selected} onOpen={openSpecimen} />}
      {page === 'reports' && <Reports selected={selected} status={reportStatus} setStatus={setReportStatus} notify={notify} />}
      {page === 'analytics' && <Analytics />}
      {page === 'audit' && <Audit />}
    </main>
    {toast && <div className="toast"><Icon name="check" size={17}/>{toast}</div>}
  </div>
}

function Tower({ onOpen, onNavigate }: { onOpen: (id: string) => void; onNavigate: (page: Page) => void }) {
  return <div className="page tower-page"><div className="hero-row"><div><span className="eyebrow">MONDAY, 31 AUGUST 2026</span><h1>Laboratory <em>Control Tower</em></h1><p>Good morning, Aria. Here’s your laboratory pulse at a glance.</p></div><button className="primary-button" onClick={() => onNavigate('specimens')}><Icon name="flask" size={17}/> Register specimen</button></div>
    <div className="kpi-grid"><KpiCard label="ACTIVE CASES" value="126" detail="Across all workflow stages" trend="+8.2%"/><KpiCard label="CASES AT RISK" value="07" detail="Require attention in 2 hours" tone="rose"/><KpiCard label="AVG. TURNAROUND" value="18.4h" detail="1.6h below weekly target" trend="↓ 8.1%" tone="teal"/><KpiCard label="SLA COMPLIANCE" value="94.8%" detail="Target is 92.0%" trend="+2.4%" tone="violet"/><KpiCard label="QUALITY SCORE" value="96.2" detail="Based on 342 checks" trend="+0.7" tone="amber"/></div>
    <div className="tower-grid"><Panel className="workflow-panel"><div className="panel-head"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>Specimen flow</h2></div><button className="text-button" onClick={() => onNavigate('workflow')}>View workflow <Icon name="arrow" size={15}/></button></div><div className="workflow-track">{workflow.map((item, index) => <div className="workflow-node" key={item.stage}><div className={`node-orb ${item.tone}`}><strong>{item.count}</strong><small>cases</small></div>{index < workflow.length - 1 && <span className="connector"/>}<div className="node-label"><strong>{item.stage}</strong><small className={item.backlog > 8 ? 'danger' : ''}>{item.backlog} in backlog</small></div></div>)}</div><div className="bottleneck"><span><Icon name="alert" size={17}/></span><div><strong>Review stage bottleneck detected</strong><p>27 cases are pending — 32% higher than the normal workload.</p></div><button onClick={() => onNavigate('workflow')}>Investigate <Icon name="arrow" size={14}/></button></div></Panel>
      <Panel className="insights-panel"><div className="panel-head"><div><span className="eyebrow">AI-ASSISTED</span><h2>Operational insights</h2></div><span className="ai-pulse"><i/> Live</span></div><div className="insight-list"><Insight tone="rose" title="4 cases approaching SLA breach" text="Review workload may impact target completion."/><Insight tone="amber" title="2 slides require quality review" text="Minor imaging flags were detected."/><Insight tone="violet" title="Review workload has increased" text="Up 32% against 7-day average."/></div><div className="recommendation"><div className="spark-icon"><Icon name="spark" size={16}/></div><div><span>AI-ASSISTED RECOMMENDATION</span><p>Reassign 3 pending cases to reduce estimated turnaround time.</p><button onClick={() => onNavigate('workflow')}>View recommendation <Icon name="arrow" size={13}/></button></div></div></Panel></div>
    <div className="bottom-grid"><Panel><div className="panel-head"><div><span className="eyebrow">PRIORITY QUEUE</span><h2>Cases requiring attention</h2></div><button className="text-button" onClick={() => onNavigate('specimens')}>View all</button></div><div className="case-list">{specimens.filter(s => s.status === 'At risk' || s.status === 'Delayed').map(s => <CaseRow key={s.id} specimen={s} onOpen={onOpen}/>)}</div></Panel><Panel className="turnaround"><div className="panel-head"><div><span className="eyebrow">PERFORMANCE</span><h2>Turnaround time</h2></div><button className="select-mini">This week⌄</button></div><div className="chart-stat"><strong>18.4<small>hrs avg.</small></strong><span>↓ 8.1% <small>vs last week</small></span></div><div className="line-chart"><svg viewBox="0 0 500 150" preserveAspectRatio="none"><path d="M0 128 L48 103 L97 112 L145 75 L195 86 L245 48 L294 65 L345 41 L396 58 L445 26 L500 35" fill="none" stroke="#64d1c0" strokeWidth="3"/><path d="M0 128 L48 103 L97 112 L145 75 L195 86 L245 48 L294 65 L345 41 L396 58 L445 26 L500 35 L500 150 L0 150Z" fill="url(#area)"/><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#64d1c0" stopOpacity=".25"/><stop offset="1" stopColor="#64d1c0" stopOpacity="0"/></linearGradient></defs></svg><div><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></Panel></div>
  </div>
}

function Insight({ tone, title, text }: { tone: string; title: string; text: string }) { return <div className="insight"><i className={tone}/><div><strong>{title}</strong><p>{text}</p></div><Icon name="chevron" size={15}/></div> }

function Specimens({ selected, query, onOpen, onNavigate }: { selected: Specimen; query: string; onOpen: (id: string) => void; onNavigate: (page: Page) => void }) {
  const [filter, setFilter] = useState('All cases'); const found = useMemo(() => specimens.filter(s => (filter === 'All cases' || s.status === filter) && `${s.id} ${s.patientId} ${s.patient} ${s.type}`.toLowerCase().includes(query.toLowerCase())), [filter, query])
  return <div className="page specimen-page"><div className="hero-row compact"><div><span className="eyebrow">CASE MANAGEMENT</span><h1>Specimens <em>registry</em></h1><p>Track every specimen through its diagnostic journey.</p></div><button className="primary-button"><Icon name="flask" size={17}/> New specimen</button></div><div className="segment-control">{['All cases', 'At risk', 'On track', 'Delayed', 'Complete'].map(x => <button className={filter === x ? 'chosen' : ''} onClick={() => setFilter(x)} key={x}>{x}{x === 'All cases' && <span>{specimens.length}</span>}</button>)}</div><div className="specimens-layout"><Panel className="table-panel"><div className="table-head"><strong>{found.length} specimens</strong><button className="filter-button">Filter <span>⌄</span></button></div><div className="spec-table"><div className="thead"><span>SPECIMEN</span><span>PRIORITY</span><span>WORKFLOW STAGE</span><span>COLLECTED</span><span>STATUS</span><span/></div>{found.map(s => <button className={`tr ${selected.id === s.id ? 'selected' : ''}`} onClick={() => onOpen(s.id)} key={s.id}><span><strong>{s.id}</strong><small>{s.patientId} · {s.type}</small></span><StatusBadge value={s.priority}/><span className="stage-cell"><i className={s.status === 'At risk' || s.status === 'Delayed' ? 'warn' : ''}/>{s.stage}</span><span className="muted">{s.collected}</span><StatusBadge value={s.status}/><Icon name="chevron" size={16}/></button>)}</div></Panel><SpecimenPreview specimen={selected} onNavigate={onNavigate}/></div></div>
}

function SpecimenPreview({ specimen, onNavigate }: { specimen: Specimen; onNavigate: (page: Page) => void }) { return <Panel className="specimen-preview"><div className="preview-top"><span className="eyebrow">SELECTED SPECIMEN</span><StatusBadge value={specimen.status}/></div><h2>{specimen.id}</h2><p>{specimen.type} <i>·</i> {specimen.patientId}</p><div className="risk-card"><span>Predictive workflow analysis</span><strong>SLA breach risk <em>{specimen.risk}</em></strong><p>Estimated completion: <b>{specimen.eta}</b></p></div><div className="preview-meta"><div><small>CURRENT STAGE</small><strong>{specimen.stage}</strong></div><div><small>ASSIGNED TO</small><strong>{specimen.assignee}</strong></div></div><div className="twin-mini"><span>SPECIMEN</span><div className="branch"><strong>BLOCK A</strong><small>└─ {specimen.slides[0]?.id ?? 'Not prepared'}</small></div><div className="branch"><strong>BLOCK B</strong><small>└─ {specimen.slides[1]?.id ?? 'Pending'}</small></div></div><button className="full-width-button" onClick={() => onNavigate('slides')}>Open digital specimen twin <Icon name="arrow" size={15}/></button></Panel> }

function Workflow() { return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">LIVE LAB OPERATIONS</span><h1>Workflow <em>command</em></h1><p>Monitor case volume, handoffs, and operational capacity.</p></div><button className="outline-button"><Icon name="clock" size={16}/> View handoff log</button></div><Panel className="command-panel"><div className="panel-head"><div><span className="eyebrow">END-TO-END FLOW</span><h2>Current laboratory workload</h2></div><span className="ai-pulse"><i/> Updated just now</span></div><div className="workflow-command">{workflow.map((w, i) => <div key={w.stage} className={`command-stage ${w.tone}`}><div><span>{String(i + 1).padStart(2, '0')}</span><h3>{w.stage}</h3></div><strong>{w.count}<small>active cases</small></strong><p><b className={w.backlog > 8 ? 'hot' : ''}>{w.backlog}</b> cases in queue</p><div className="capacity"><i style={{width: `${Math.min(100, w.count * 2.7)}%`}}/></div>{w.backlog > 8 && <small className="hot">Elevated backlog</small>}</div>)}</div></Panel><div className="bottom-grid"><Panel><div className="panel-head"><div><span className="eyebrow">RECOMMENDED ACTION</span><h2>Balance review workload</h2></div><div className="spark-icon"><Icon name="spark"/></div></div><p className="body-copy">Assigning 3 pending cases to Dr. Sameer Rao would reduce the Review queue by 11% and bring two at-risk cases inside SLA.</p><button className="primary-button">Apply recommendation <Icon name="arrow" size={15}/></button></Panel><Panel><span className="eyebrow">STAFFING</span><h2>Review team capacity</h2><div className="staff-list"><div><Avatar name="Kavya Mehta" small/><span>Dr. Kavya Mehta<small>12 cases assigned</small></span><b className="danger">High load</b></div><div><Avatar name="Sameer Rao" small/><span>Dr. Sameer Rao<small>6 cases assigned</small></span><b className="good">Available</b></div></div></Panel></div></div> }

function Slides({ selected, onSelect }: { selected: Specimen; onSelect: (id: string) => void }) { const [slide, setSlide] = useState<Slide | null>(selected.slides[0] ?? null); const all = specimens.flatMap(s => s.slides.map(x => ({...x, specimen: s}))); return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">DIGITAL TWIN</span><h1>Slide <em>tracking</em></h1><p>Trace slides, blocks, stains, and quality status from one view.</p></div><button className="outline-button">Scan barcode</button></div><div className="slides-layout"><Panel className="slide-table"><div className="panel-head"><div><span className="eyebrow">ACTIVE SLIDES</span><h2>{all.length} in laboratory</h2></div></div>{all.map(x => <button onClick={() => {setSlide(x); onSelect(x.specimen.id)}} className={`slide-row ${slide?.id === x.id ? 'selected' : ''}`} key={x.id}><div className="slide-graphic"><i/></div><span><strong>{x.id}</strong><small>{x.specimen.id} · {x.block}</small></span><span>{x.stain}</span><StatusBadge value={x.qc}/><Icon name="chevron" size={15}/></button>)}</Panel><Panel className="slide-detail">{slide ? <><div className="slide-detail-hero"><div className="large-slide"><i/></div><div><span className="eyebrow">SLIDE DETAIL</span><h2>{slide.id}</h2><p>{selected.id} · {slide.block}</p></div></div><div className="detail-grid"><div><small>STAIN TYPE</small><strong>{slide.stain}</strong></div><div><small>WORKFLOW STATUS</small><strong>{slide.status}</strong></div><div><small>QUALITY STATUS</small><StatusBadge value={slide.qc}/></div><div><small>QUALITY SCORE</small><strong>{slide.score}/100</strong></div></div><div className="slide-tree"><span>SPECIMEN <b>{selected.id}</b></span><div>└── <b>{slide.block}</b><div>└── <em>{slide.id}</em></div></div></div><button className="full-width-button">View full slide image <Icon name="arrow" size={15}/></button></> : <p>No slides have been prepared for this specimen.</p>}</Panel></div></div> }

function Quality({ selected, onOpen }: { selected: Specimen; onOpen: (id: string) => void }) { const flagged = specimens.flatMap(s => s.slides.filter(x => x.qc !== 'Pass').map(x => ({...x, specimen: s}))); return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">QUALITY ASSURANCE</span><h1>Quality <em>control</em></h1><p>AI-assisted operational checks, always requiring human verification.</p></div><button className="outline-button"><Icon name="file" size={16}/> Export QC summary</button></div><div className="quality-kpis"><KpiCard label="QUALITY PASS RATE" value="96.2%" detail="Based on 342 slide checks" trend="+0.7%" tone="teal"/><KpiCard label="REQUIRES REVIEW" value="03" detail="Slides awaiting verification" tone="rose"/><KpiCard label="AVERAGE SCORE" value="94.8" detail="Across scanned slides" trend="+1.2" tone="violet"/></div><div className="qc-layout"><Panel className="qc-main"><div className="panel-head"><div><span className="eyebrow">FLAGGED FOR HUMAN REVIEW</span><h2>Quality assessment queue</h2></div><StatusBadge value="Requires Review"/></div>{flagged.map(x => <button className="qc-row" onClick={() => onOpen(x.specimen.id)} key={x.id}><div className="score-ring" style={{'--score': `${x.score}%`} as React.CSSProperties}><b>{x.score}</b></div><div><strong>{x.id}</strong><p>{x.specimen.id} · {x.stain}</p></div><div className="flags">{x.flags.map(f => <span key={f}>{f}</span>)}</div><StatusBadge value={x.qc}/><Icon name="chevron" size={15}/></button>)}</Panel><Panel className="assessment"><div className="spark-icon"><Icon name="spark" size={16}/></div><span className="eyebrow">AI-ASSISTED QUALITY ASSESSMENT</span><h2>{selected.slides[0]?.id ?? 'No slide selected'}</h2><div className="assessment-score"><strong>{selected.slides[0]?.score ?? '—'}</strong><span>/ 100<br/><small>quality score</small></span></div><p>Image characteristics have been assessed for operational quality only. This is not a diagnostic result.</p><div className="disclaimer"><Icon name="shield" size={17}/><span>Requires pathologist verification before clinical use.</span></div><button className="full-width-button">Flag for human review <Icon name="arrow" size={14}/></button></Panel></div></div> }

function Reports({ selected, status, setStatus, notify }: { selected: Specimen; status: ReportStatus; setStatus: (x: ReportStatus) => void; notify: (x: string) => void }) { return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">REPORT MANAGEMENT</span><h1>Diagnostic <em>reports</em></h1><p>Prepare, review, and approve reports with clear accountability.</p></div><StatusBadge value={status}/></div><div className="reports-layout"><Panel className="report-document"><div className="document-head"><div className="document-logo">PF</div><div><strong>PATHOFLOW DIAGNOSTICS</strong><small>Histopathology Report</small></div><span>Case {selected.id}</span></div><div className="report-section two-col"><div><small>PATIENT</small><p>{selected.patient}<br/>{selected.patientId}</p></div><div><small>SPECIMEN</small><p>{selected.type}<br/>{selected.collected}</p></div></div><div className="report-section"><small>CLINICAL FINDINGS</small><p>The tissue sections show morphology consistent with the preliminary diagnostic impression. Correlation with clinical and imaging findings is advised.</p></div><div className="report-section diagnosis"><small>DIAGNOSIS</small><p>{selected.diagnosis}</p></div><div className="report-section"><small>COMMENTS</small><p>This report is a prototype using fictional, de-identified patient data. Final sign-out requires pathologist review.</p></div><div className="signature"><span>Prepared by <b>Dr. Kavya Mehta</b></span><span>Last updated <b>31 Aug 2026, 02:11 PM</b></span></div></Panel><div className="report-side"><Panel className="ai-draft"><div className="spark-icon"><Icon name="spark"/></div><span>AI DRAFT — REQUIRES PATHOLOGIST APPROVAL</span><p>Draft content is structured from demo case information and must be verified before approval.</p><button onClick={() => notify('AI draft outline refreshed.')}>Refresh draft <Icon name="arrow" size={14}/></button></Panel><Panel><span className="eyebrow">REPORT STATUS</span><h2>{status}</h2><div className="status-stepper">{(['Draft', 'Under Review', 'Approved'] as ReportStatus[]).map(x => <button className={status === x ? 'active' : ''} key={x} onClick={() => setStatus(x)}><i/>{x}</button>)}</div><button className="primary-button full" onClick={() => {setStatus('Approved'); notify('Report approved and added to audit trail.')}}><Icon name="check" size={16}/> Approve final report</button></Panel></div></div></div> }

function Analytics() { const bars = [42, 55, 49, 72, 61, 82, 68]; return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">LABORATORY INTELLIGENCE</span><h1>Performance <em>analytics</em></h1><p>Meaningful operational metrics for faster, safer diagnostic workflows.</p></div><button className="outline-button">Last 30 days⌄</button></div><div className="analytics-grid"><Panel className="analytics-chart"><div className="panel-head"><div><span className="eyebrow">TURNAROUND TIME</span><h2>Average completion trend</h2></div><strong className="metric-green">18.4h <small>↓ 8.1%</small></strong></div><div className="bar-chart">{bars.map((x, i) => <div key={i}><i style={{height: `${x}%`}}/><span>{['M','T','W','T','F','S','S'][i]}</span></div>)}</div></Panel><Panel><span className="eyebrow">SLA COMPLIANCE</span><h2>94.8%</h2><div className="donut"><div><strong>94.8</strong><small>target 92%</small></div></div><p className="muted">Above the operational target for the third consecutive week.</p></Panel><Panel><span className="eyebrow">WORKFLOW MIX</span><h2>Cases by stage</h2><div className="stage-bars">{workflow.slice(1).map(x => <div key={x.stage}><span>{x.stage}</span><i><b style={{width: `${x.count * 2.5}%`}}/></i><strong>{x.count}</strong></div>)}</div></Panel><Panel><span className="eyebrow">QUALITY</span><h2>Pass rate by stain</h2><div className="quality-lines"><div><span>H&E</span><i><b style={{width:'98%'}}/></i><strong>98%</strong></div><div><span>IHC</span><i><b style={{width:'94%'}}/></i><strong>94%</strong></div><div><span>Special</span><i><b style={{width:'91%'}}/></i><strong>91%</strong></div></div></Panel></div></div> }

function Audit() { const events = specimens[0].events; return <div className="page"><div className="hero-row compact"><div><span className="eyebrow">TRACEABILITY</span><h1>Audit <em>trail</em></h1><p>A chronological, tamper-evident view of key laboratory actions.</p></div><button className="outline-button">Export activity log</button></div><Panel className="audit-panel"><div className="panel-head"><div><span className="eyebrow">CASE ACTIVITY</span><h2>PATH-004821</h2></div><StatusBadge value="At risk"/></div><div className="timeline">{events.map((event, i) => <div className={`timeline-event ${event.status}`} key={event.title}><i>{event.status === 'complete' ? <Icon name="check" size={12}/> : i + 1}</i><div><span>{event.time}</span><h3>{event.title}</h3><p>{event.note}</p><small>{event.person}</small></div></div>)}</div></Panel></div> }
